spring:
  datasource:
    url: jdbc:mysql://mutsa-db.clkqgkc8ybn7.ap-northeast-2.rds.amazonaws.com:3306/mutsa_practice6
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        #        use_sql_comments: true
        hbm2ddl:
          auto: update #create
        default_batch_fetch_size: 1000
  security:
    oauth2:
      client:
        registration:
          kakao: # 카카오 로그인 설정
            client-id: ${CLIENT_ID}  # 환경변수로 설정 (보안상 중요!)
            client-secret: ${CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: https://yeogaeng.shop/auth/kakao
            client-name: Kakao
        provider:
          kakao: # 카카오 OAuth2 제공자 설정
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id  # 카카오에서 사용자 식별자로 사용할 속성

  # JWT 토큰 설정
  jwt:
    secret: my-secret-key-study-springboot-psbsbb
    # Access Token: 짧은 만료시간 (보안 강화)
    access-token-expiration: 3600000    # 1시간 (1 * 60 * 60 * 1000)
    # Refresh Token: 긴 만료시간 (사용자 편의성)
    refresh-token-expiration: 1209600000 # 14일 (14 * 24 * 60 * 60 * 1000)