spring:
  datasource:
    url: jdbc:mysql://mutsa-db.clkqgkc8ybn7.ap-northeast-2.rds.amazonaws.com:3306/mutsa_practice6
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        #        use_sql_comments: true
        hbm2ddl:
          auto: update #create
        default_batch_fetch_size: 1000