spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        # use_sql_comments: true
        hbm2ddl:
          auto: update  # 배포 시에는 validate 또는 none 권장
        default_batch_fetch_size: 1000

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000       # 1시간 (1 * 60 * 60 * 1000)
  refresh-token-expiration: 1209600000   # 14일 (14 * 24 * 60 * 60 * 1000)

kakao:
  client-id: ${KAKAO_API_KEY}
  client-secret: ${KAKAO_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  auth-uri: https://kauth.kakao.com/oauth/authorize
  token-uri: https://kauth.kakao.com/oauth/token
  user-info-uri: https://kapi.kakao.com/v2/user/me

logging:
  level:
    root: INFO
    mutsa.mutsa_practice6: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.filter: DEBUG