
spring:
  datasource:
    url: jdbc:mysql://database-1.c8nim0400lf9.us-east-1.rds.amazonaws.com:3306/mutsa_board
    username: admin
    password: Wmfrjqrp9314*

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
