
spring:
  datasource:
    url: jdbc:mysql://database-1.c8nim0400lf9.us-east-1.rds.amazonaws.com:3306/mutsa_board
    username: admin
    password: Wmfrjqrp9314*

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:  # 카카오 로그인 설정
            client-id: c01ce5e3e57aec3ef59b188657f72b1d  # 환경변수로 설정 (보안상 중요!)
            client-secret: VVM9jFUt7RatlcADF2TomPPRACdGBDeE
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
        provider:
          kakao:  # 카카오 OAuth2 제공자 설정
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id  # 카카오에서 사용자 식별자로 사용할 속성

# JWT 토큰 설정
jwt:
  secret: my-secret-key-study-springboot-psbsbb
  # Access Token: 짧은 만료시간 (보안 강화)
  access-token-expiration: 3600000    # 1시간 (1 * 60 * 60 * 1000)
  # Refresh Token: 긴 만료시간 (사용자 편의성)
  refresh-token-expiration: 1209600000
