# default 공통 설정
spring:
  datasource:
    url: jdbc:mysql://mutsa-db.c9c6sgcw26xh.ap-southeast-2.rds.amazonaws.com:3306/mutsa_board
    username: gwanghwi
    password: ${DB_PASSWORD:dummy-db-password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  # 콘솔에 sql 출력
    properties:
      hibernate:
        format_sql: true

  jwt:
    secret: ${JWT_SECRET:dummy-jwt-secret}

kakao:
  client-id: ${KAKAO_CLIENT_ID:dummy-client-id}
  client-secret: ${KAKAO_CLIENT_SECRET:dummy-client-secret}
  redirect-uri: ${KAKAO_REDIRECT_URI:https://dummy.local/callback}